#ifndef BASEWEBSOCKETINPUT_GLOBAL_H
#define BASEWEBSOCKETINPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEWEBSOCKETINPUT_LIBRARY)
#  define BASEWEBSOCKETINPUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASEWEBSOCKETINPUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEWEBSOCKETINPUT_GLOBAL_H
