#ifndef SMOOTHSURFACE_GLOBAL_H
#define SMOOTHSURFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMOOTHSURFACE_LIBRARY)
#  define SMOOTHSURFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SMOOTHSURFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SMOOTHSURFACE_GLOBAL_H
