#ifndef HORIZONTALSTACK_GLOBAL_H
#define HORIZONTALSTACK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HORIZONTALSTACK_LIBRARY)
#  define HORIZONTALSTACKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HORIZONTALSTACKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HORIZONTALSTACK_GLOBAL_H
