#ifndef TEMPLATEFILTER_GLOBAL_H
#define TEMPLATEFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLATEFILTER_LIBRARY)
#  define TEMPLATEFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPLATEFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATEFILTER_GLOBAL_H
