#ifndef WEBSOCKETINPUT_GLOBAL_H
#define WEBSOCKETINPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBSOCKETINPUT_LIBRARY)
#  define WEBSOCKETINPUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBSOCKETINPUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBSOCKETINPUT_GLOBAL_H
