#ifndef ORIENTATION2COORD_GLOBAL_H
#define ORIENTATION2COORD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ORIENTATION2COORD_LIBRARY)
#  define ORIENTATION2COORDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ORIENTATION2COORDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ORIENTATION2COORD_GLOBAL_H
