#ifndef GRIDINPUTFILE_GLOBAL_H
#define GRIDINPUTFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRIDINPUTFILE_LIBRARY)
#  define GRIDINPUTFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRIDINPUTFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRIDINPUTFILE_GLOBAL_H
