#ifndef AREADATETIME_GLOBAL_H
#define AREADATETIME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AREADATETIME_LIBRARY)
#  define AREADATETIMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AREADATETIMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AREADATETIME_GLOBAL_H
